# Generated by Django 5.1.15 on 2026-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='eskiz', max_length=32)),
                ('eskiz_email', models.CharField(blank=True, max_length=128)),
                ('eskiz_password', models.CharField(blank=True, max_length=128)),
                ('eskiz_sender', models.CharField(default='4546', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS sozlamalari',
            },
        ),
    ]
