# Generated by Django 5.1.15 on 2026-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('main', 'Asosiy'), ('support', 'Yordamchi (support)')], default='main', max_length=16),
        ),
    ]
