# Generated by Django 5.1.15 on 2026-04-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', "O'qituvchi"), ('student', "O'quvchi"), ('parent', 'Ota-ona')], default='admin', max_length=16),
        ),
    ]
