# Generated by Django 5.0.6 on 2026-04-23 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advance',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancerequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_requests', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='finalized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='advance',
            index=models.Index(fields=['teacher', 'year', 'month'], name='salary_adva_teacher_c7bc95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('teacher', 'year', 'month')},
        ),
    ]
