# Generated by Django 5.1.15 on 2026-04-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_sync_group_to_groups'),
        ('teachers', '0003_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referrer_source',
            field=models.CharField(blank=True, help_text='Tashqi manba: Instagram, Telegram, reklama va hk.', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='referrer_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='students.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='referrer_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='teachers.teacher'),
        ),
    ]
