# Generated by Django 5.1.15 on 2026-04-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_initial'),
        ('teachers', '0003_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='support_teacher',
            field=models.ForeignKey(blank=True, help_text="Yordamchi (support) o'qituvchi", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_groups', to='teachers.teacher'),
        ),
    ]
