# Generated by Django 5.1.15 on 2026-04-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_support_teacher'),
        ('students', '0005_student_referrer_source_student_referrer_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(help_text="Guruhga qo'shilgan sana")),
                ('left_at', models.DateField(blank=True, help_text='Guruhdan chiqqan sana', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'group'], name='groups_grou_student_0035d6_idx'), models.Index(fields=['group', 'enrolled_at'], name='groups_grou_group_i_1dee95_idx')],
            },
        ),
    ]
